name: chat_composer
description: A Flutter package for easy implementation of chat composer allows users to chat with Text, Audio, and Other Media.
version: 1.0.3
homepage: https://github.com/anokabb/chat_composer

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=3.2.1"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.4
  path_provider: ^2.1.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.1.0
  audio_session: ^0.1.18
  plugin_platform_interface: ^2.1.7
#  record:
#    path: ../record/record

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - packages/chat_composer/images/delete_icon.png
